name: .NET Build

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  dotnet-build:
    uses: Yellow-Dog-Man/composite-actions-templates/.github/workflows/generic-dotnet-build.yml@main
    with:
      dotnet_project: Verify.Marshaling
      artifact_name: binary
      dotnet_build_path: '**/bin/**/**/*.dll'
  dotnet-test:
    uses: Yellow-Dog-Man/composite-actions-templates/.github/workflows/generic-dotnet-tests.yml@main
